# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.21',
        :net => [
                   {ip: '192.168.3.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "router-net"},
                   {ip: '192.168.2.2', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "router-net"},
                   {ip: '192.168.1.2', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "router-net"}
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.22',
        :net => [
                   {ip: '192.168.3.3', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "router-net"},
                   {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "router-net"},
                   {ip: '192.168.2.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "router-net"}
                ]
  },
   :testClient1 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.11',
        :net => [
                   {adapter: 3, auto_config: false, virtualbox__intnet: true},
                   {adapter: 4, auto_config: false, virtualbox__intnet: true}
                ]
  }, 
   :testClient2 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.12',
        :net => [
                   {adapter: 3, auto_config: false, virtualbox__intnet: true},
                   {adapter: 4, auto_config: false, virtualbox__intnet: true}
                ]
  }, 
  :testServer1 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.13',
        :net => [
                   {adapter: 3, auto_config: false, virtualbox__intnet: true},
                   {adapter: 4, auto_config: false, virtualbox__intnet: true},
                ]
  },
  :testServer2 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.14',
        :net => [
                   {adapter: 3, auto_config: false, virtualbox__intnet: true},
                   {adapter: 4, auto_config: false, virtualbox__intnet: true},
                ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end
        box.vm.network "private_network", ip: boxconfig[:ip_addr]
        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          yum install sudo -y
          groupadd sudo 
          sudo su
          useradd mora -G sudo -d /home/mora -s /bin/bash 
          usermod -aG sudo vagrant 
          cat /vagrant/sudoers > /etc/sudoers
          mkdir /home/mora/.ssh 
          cp /vagrant/id_rsa.pub /home/mora/.ssh/authorized_keys
          chown mora:mora -R /home/mora
          setenforce 0
            SHELL
        when "centralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          yum install sudo -y
          groupadd sudo 
          sudo su
          useradd mora -G sudo -d /home/mora -s /bin/bash 
          usermod -aG sudo vagrant 
          cat /vagrant/sudoers > /etc/sudoers
          mkdir /home/mora/.ssh 
          cp /vagrant/id_rsa.pub /home/mora/.ssh/authorized_keys
          chown mora:mora -R /home/mora
          setenforce 0
            SHELL
        when "testClient1"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          yum install sudo -y
          groupadd sudo 
          sudo su
          useradd mora -G sudo -d /home/mora -s /bin/bash 
          usermod -aG sudo vagrant 
          cat /vagrant/sudoers > /etc/sudoers
          mkdir /home/mora/.ssh 
          cp /vagrant/id_rsa.pub /home/mora/.ssh/authorized_keys
          chown mora:mora -R /home/mora
          setenforce 0
            SHELL
        when "testClient2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          yum install sudo -y
          groupadd sudo 
          sudo su
          useradd mora -G sudo -d /home/mora -s /bin/bash 
          usermod -aG sudo vagrant 
          cat /vagrant/sudoers > /etc/sudoers
          mkdir /home/mora/.ssh 
          cp /vagrant/id_rsa.pub /home/mora/.ssh/authorized_keys
          chown mora:mora -R /home/mora
          setenforce 0
            SHELL
        when "testServer1"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          yum install sudo -y
          groupadd sudo 
          sudo su
          useradd mora -G sudo -d /home/mora -s /bin/bash 
          usermod -aG sudo vagrant 
          cat /vagrant/sudoers > /etc/sudoers
          mkdir /home/mora/.ssh 
          cp /vagrant/id_rsa.pub /home/mora/.ssh/authorized_keys
          chown mora:mora -R /home/mora
          setenforce 0
            SHELL
        when "testServer2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          yum install sudo -y
          groupadd sudo 
          sudo su
          useradd mora -G sudo -d /home/mora -s /bin/bash 
          usermod -aG sudo vagrant 
          cat /vagrant/sudoers > /etc/sudoers
          mkdir /home/mora/.ssh 
          cp /vagrant/id_rsa.pub /home/mora/.ssh/authorized_keys
          chown mora:mora -R /home/mora
          setenforce 0
            SHELL

        end

      end

  end
  
  
end
