MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101'
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end

          box.vm.provision :shell do |s|
             s.inline = 'mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh'
          end
 	      box.vm.provision "shell", inline: <<-SHELL
          yum install -y vim mc apache2 curl epel-release
          curl -O https://owncloud.research.ru.com/index.php/s/S4SdOyGW6FQdEO4/download
          mv ./download /usr/local/bin/timer
          chmod u+x /usr/local/bin/timer 
          curl -O https://owncloud.research.ru.com/index.php/s/cwtHJ6y5TKfbRzm/download
          mv ./download /etc/systemd/system/otus_timer.timer 
          curl -O https://owncloud.research.ru.com/index.php/s/vrbiSouY3uqWQu0/download
          mv ./download /etc/systemd/system/otus_timer.service
          chmod 755 /etc/systemd/system/otus*
          systemctl daemon-reload 
          systemctl start otus_timer.timer
          systemctl enable otus_timer.timer 
          yum update 
          yum install -y spawn-fcgi php php-cli mod_fcgid httpd
          curl -O https://owncloud.research.ru.com/index.php/s/nnR7GxG2DFTQ1qX/download
          mv ./download /etc/sysconfig/spawn-fcgi
          curl -O https://owncloud.research.ru.com/index.php/s/UozjjRGNRnZr3AY/download
          mv ./download /etc/systemd/system/spawn-fcgi.service
          cp /usr/lib/systemd/system/httpd.service /etc/systemd/system/httpd1.service
          sed -i '9s/httpd/httpd1/' /etc/systemd/system/httpd1.service 
          cp /etc/sysconfig/httpd /etc/sysconfig/httpd1
          systemctl daemon-reload 
          systemctl start spawn-fcgi 
  	  SHELL

      end
  end
end
