---
        - name: Install nginx kibana logstash
          yum: 
            name: 
                - nginx 
                - kibana
                - logstash
            state: latest 
        - name: Copy configuration 
          shell: "cp /vagrant/grok.conf /etc/logstash/conf.d ; cat /vagrant/kibana.yml > /etc/kibana/kibana.yml ; cat /vagrant/nginx.conf > /etc/nginx/nginx.conf "
          register: shell_result 
        - name: start and enable 
          systemd:
            state: started 
            enabled: yes
            name: '{{item}}'
          with_items: ['kibana','nginx','logstash']

