# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.11.101"
    server.vm.provision "shell", run: "always", inline: <<-SHELL
    SHELL
  end
  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.11.102"
    client.vm.provision "shell", run: "always", inline: <<-SHELL
    SHELL
 end
end 
