# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :ansible => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150',
  },
  :web => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.151',
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "256"]
        #   vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          vb.name = boxname.to_s

        #   boxconfig[:disks].each do |dname, dconf|
        #       unless File.exist?(dconf[:dfile])
        #         vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
        #       end
        #       vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
        # end
          end
      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL

      case boxname.to_s
      when "ansible"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          yum install epel-release -y
          yum install ansible vim python3 python-simplejson openssh-server -y
          cp /vagrant/id_rs* /home/vagrant/.ssh/
          chown vagrant:vagrant /home/vagrant/.ssh/id_rsa 
          chmod 0600 /home/vagrant/.ssh/id_rsa
          chmod 644 /home/vagrant/.ssh/id_rsa.pub
          cp /vagrant/ansible.cfg /home/vagrant/ 
          cp /vagrant/inventory.cfg /home/vagrant 
          cp /vagrant/otus_playbook  ./
          SHELL
      when "web"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
        yum install openssh-server vim python3 python-simplejson epel-release -y 
        cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
        chown vagrant:vagrant /home/vagrant
        chmod 700 -R /home/vagrant 
        SHELL
      end

      end
   end
end
