# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :server => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150',
  },
  :client => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.151',
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "2048"]
        #   vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          vb.name = boxname.to_s

        #   boxconfig[:disks].each do |dname, dconf|
        #       unless File.exist?(dconf[:dfile])
        #         vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
        #       end
        #       vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
        # end
          end
      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL

      case boxname.to_s
      when "server"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          cp /vagrant/elk.repo /etc/yum.repos.d/
          setenforce 0
          yum install dnf epel-release -y 
          yum install nginx -y
          dnf localinstall /vagrant/jre-8u241-linux-x64.rpm -y 
          yum install vim kibana elasticsearch logstash filebeat -y
          cp /vagrant/grok.conf /etc/logstash/conf.d
          cp /vagrant/nginx.conf /etc/nginx/
          cp /vagrant/rsyslog.conf /etc/
          cp /vagrant/filebeat.yml /etc/filebeat 
          systemctl start logstash elasticsearch kibana nginx filebeat  
          systemctl restart rsyslog 
          SHELL
      when "client"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
        yum install epel-release -y
        yum install nginx -y
        cp /vagrant/nginx.conf2 /etc/nginx/nginx.conf 
        cp /vagrant/main.conf /etc/rsyslog.d/
        systemctl restart rsyslog nginx   
        SHELL
      end

      end
   end
end
