MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101'
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end

          box.vm.provision :shell do |s|
             s.inline = 'mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh'
          end
 	      box.vm.provision "shell", inline: <<-SHELL
          yum install -y vim mc apache2 curl epel-release wget rpm-build createrepo yum-utils rpmdevtools redhat-lsb-core gcc 
          yum localinstall -y /vagrant/nginx-1.16.1-1.el7.ngx.x86_64.rpm
          rm /etc/nginx/conf.d/default.conf
          cp /vagrant/default.conf /etc/nginx/conf.d/default.conf
          mkdir /usr/share/nginx/html/repo 
          cp /vagrant/nginx-1.16.1-1.el7.ngx.x86_64.rpm /usr/share/nginx/html/repo
          wget http://www.percona.com/downloads/percona-release/redhat/0.1-6/percona-release-0.1-6.noarch.rpm -O /usr/share/nginx/html/repo/percona-release-0.1-6.noarch.rpm
          createrepo /usr/share/nginx/html/repo
          systemctl start nginx 
          cp /vagrant/otus.repo /etc/yum.repos.d/
  	  SHELL

      end
  end
end
