# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
MACHINES = {
  :client => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150'
  },
  :server => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.151'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "256"]
        #   vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          vb.name = boxname.to_s
          end
      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL

      case boxname.to_s
      when "client"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          yum install -y vim mc bacula-client 
          cat /vagrant/fd > /etc/bacula/bacula-fd.conf 
          setenforce 0
          mkdir /var/lib/bacula 
          chown bacula:bacula -R /var/lib/bacula 
          systemctl start bacula-fd 
          SHELL
      when "server"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
        yum install -y vim mc bacula-director bacula-storage bacula-console mariadb-server
        systemctl start mariadb  
        setenforce 0 
        /usr/libexec/bacula/grant_mysql_privileges
        /usr/libexec/bacula/create_mysql_database -u root
        /usr/libexec/bacula/make_mysql_tables -u bacula 
        mysql -e "grant all on bacula.* to bacula@'localhost' identified by 'password';"
        echo "1
" | alternatives --config libbaccats.so 
        cat /vagrant/dir > /etc/bacula/bacula-dir.conf 
        cat /vagrant/sd > /etc/bacula/bacula-sd.conf
        cat /vagrant/bconsole > /etc/bacula/bconsole.conf 
        mkdir /backup 
        mkdir /var/lib/bacula 
        chown bacula:bacula -R /backup 
        chown bacula:bacula -R /var/lib/bacula 
        systemctl start bacula-dir bacula-sd 
echo " label pool=mainpool 
1
exit
" | bconsole 
echo " run job=client-job
yes
exit
" | bconsole 
        SHELL
      end

      end
   end
end
