MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101'
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end

          box.vm.provision :shell do |s|
             s.inline = 'mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh'
          end
 	      box.vm.provision "shell", inline: <<-SHELL
          yum install -y vim mc openssh-server
          cat /vagrant/sshd > /etc/pam.d/sshd
          cp /vagrant/test_login.sh /usr/local/bin
          adduser test 
          groupadd admin 
          gpasswd -a test admin 
          mkdir /home/test/.ssh
          cat /vagrant/id_rsa.pub > /home/test/.ssh/authorized_keys
          chmod 700 /home/test/.ssh 
          chmod 600 /home/test/.ssh/authorized_keys
          chown test:test -R /home/test
  	  SHELL

      end
  end
end
