# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :lvm => {
        :box_name => "centos/7",
        :box_version => "1804.02",
        :ip_addr => '192.168.11.101',
    :disks => {
        :sata1 => {
            :dfile => home + '/VirtualBox VMs/sata1.vdi',
            :size => 42000,
            :port => 1
        },
        :sata2 => {
            :dfile => home + '/VirtualBox VMs/sata2.vdi',
            :size => 2048, # Megabytes
            :port => 2
        },
        :sata3 => {
            :dfile => home + '/VirtualBox VMs/sata3.vdi',
            :size => 1024, # Megabytes
            :port => 3
        },
        :sata4 => {
            :dfile => home + '/VirtualBox VMs/sata4.vdi',
            :size => 1024,
            :port => 4
        }
    }
  },
}

Vagrant.configure("2") do |config|

    config.vm.box_version = "1804.02"
    MACHINES.each do |boxname, boxconfig|
  
        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
  
            #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
  
            box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "256"]
                    needsController = false
            boxconfig[:disks].each do |dname, dconf|
                unless File.exist?(dconf[:dfile])
                  vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                  needsController =  true
                            end
  
            end
                    if needsController == true
                       vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                       boxconfig[:disks].each do |dname, dconf|
                           vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                       end
                    end
            end
  
        box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            yum install -y mdadm smartmontools hdparm gdisk rsync mc
            pvcreate /dev/sdb /dev/sdc /dev/sdd
	    vgextend VolGroup00 /dev/sdb
	    vgextend VolGroup00 /dev/sdc 
	    vgextend VolGroup00 /dev/sdd 
	    lvcreate -n root -L8G VolGroup00
	    lvcreate -m1 -L2G -n var VolGroup00
	    lvcreate -n home -L5G VolGroup00
	    mkfs.xfs /dev/VolGroup00/root
	    mkfs.xfs /dev/VolGroup00/home
	    mkfs.xfs /dev/VolGroup00/var
	    mount /dev/VolGroup00/root /mnt 
	    mkdir /mnt/home
	    mkdir /mnt/var
	    mount /dev/VolGroup00/home /mnt/home
	    mount /dev/VolGroup00/var /mnt/var
	    cp -rxa / /mnt 
	    rm -rf /mnt/boot/* 
	    sed -i 's/LogVol00/root/' /mnt/etc/fstab
	    sed -i 's/LogVol00/root/' /boot/grub2/grub.cfg
	    sed -i 's/LogVol00/root/' /boot/grub2/grub.cfg
	    echo  '/dev/VolGroup00/home /home xfs defaults 0 2' >> /mnt/etc/fstab
	    echo  '/dev/VolGroup00/var /var xfs defaults 0 2' >> /mnt/etc/fstab
	    shutdown -r now 
	    lvreduce -r -L8G /dev/VolGroup00/LogVol00
            SHELL
  
        end
    end
  end
  
