# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.define "post" do |post|
    post.vm.hostname = "post"
    post.vm.network "private_network", ip: "192.168.11.101"
    post.vm.provision "shell", run: "always", inline: <<-SHELL
    SHELL
  end
end
